"""Make UserTask.attempts not nullable

Revision ID: 73f338dac5e8
Revises: cc896847c8f6
Create Date: 2025-10-13 12:45:05.566704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f338dac5e8'
down_revision = 'cc896847c8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
